### PR TITLE
adding disqus features

### PR DESCRIPTION
**Pull request by aliifam**
I am already adding disqus in this pull request by adding disqus.html file in _includes folder  for disqus component and modify _config.yml for adding your disqus shortname and modify post.html file in _layout folder for add disqus component. I am already do this in [my blog](https://notes.aliif.space/) and this work well.

### CODE REVIEW

**Comment by P0WEX** [comment]
Thanks for your contribution! 
I will consider to merge anytime soon!

**Comment by aliifam** [comment]
@P0WEX okay I'll wait until it's merged

**Comment by P0WEX** [comment]
I merged but seems to be some error with it.

**Comment by aliifam** [comment]
> I merged but seems to be some error with it.

That's because I not yet adding this domain to whitelist of site who have access to load my disqus shortname, now I already fix this by adding this domain to whitelist check at https://p0wex.github.io/Gesko/

**Pull request merged**
